// prisma/seed.ts
import { PrismaClient, PackageType, Role } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // ── Users
  const adminHash = await bcrypt.hash('Admin@123', 12);
  const userHash = await bcrypt.hash('Demo@123', 12);

  const admin = await prisma.user.upsert({
    where: { email: 'admin@tripinminutes.com' },
    update: {},
    create: {
      email: 'admin@tripinminutes.com',
      firstName: 'Super',
      lastName: 'Admin',
      passwordHash: adminHash,
      role: Role.ADMIN,
      isEmailVerified: true,
    },
  });

  const demoUser = await prisma.user.upsert({
    where: { email: 'demo@tripinminutes.com' },
    update: {},
    create: {
      email: 'demo@tripinminutes.com',
      firstName: 'Priya',
      lastName: 'Sharma',
      passwordHash: userHash,
      role: Role.USER,
      isEmailVerified: true,
      phone: '+919876543210',
    },
  });

  console.log('✅ Users seeded');

  // ── Destinations
  const destinations = [
    { name: 'Maldives', country: 'Maldives', continent: 'Asia', isDomestic: false, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800', description: 'Paradise islands with crystal waters', images: [] },
    { name: 'Dubai', country: 'UAE', continent: 'Asia', isDomestic: false, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800', description: 'City of gold and luxury', images: [] },
    { name: 'Thailand', country: 'Thailand', continent: 'Asia', isDomestic: false, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800', description: 'Land of smiles', images: [] },
    { name: 'Switzerland', country: 'Switzerland', continent: 'Europe', isDomestic: false, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800', description: 'Alpine perfection', images: [] },
    { name: 'Bali', country: 'Indonesia', continent: 'Asia', isDomestic: false, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800', description: 'Island of gods', images: [] },
    { name: 'Japan', country: 'Japan', continent: 'Asia', isDomestic: false, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800', description: 'Ancient meets ultra-modern', images: [] },
    { name: 'Kashmir', country: 'India', continent: 'Asia', isDomestic: true, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1609766418204-94aae0ecfdfc?w=800', description: 'Paradise on earth', images: [] },
    { name: 'Goa', country: 'India', continent: 'Asia', isDomestic: true, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800', description: 'Sun, sand and sea', images: [] },
    { name: 'Kerala', country: 'India', continent: 'Asia', isDomestic: true, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800', description: "God's own country", images: [] },
    { name: 'Rajasthan', country: 'India', continent: 'Asia', isDomestic: true, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800', description: 'Land of kings', images: [] },
    { name: 'Ladakh', country: 'India', continent: 'Asia', isDomestic: true, isPopular: true, coverImage: 'https://images.unsplash.com/photo-1598346762291-aee88549193f?w=800', description: 'The land of high passes', images: [] },
  ];

  const destMap: Record<string, string> = {};
  for (const d of destinations) {
    const slug = d.name.toLowerCase().replace(/\s+/g, '-');
    const dest = await prisma.destination.upsert({
      where: { slug },
      update: {},
      create: { ...d, slug },
    });
    destMap[d.name] = dest.id;
  }
  console.log('✅ Destinations seeded');

  // ── Packages
  const packages = [
    {
      title: 'Magical Maldives Overwater Escape',
      type: PackageType.INTERNATIONAL,
      destinationId: destMap['Maldives'],
      duration: 5,
      basePrice: 89999,
      discountedPrice: 79999,
      badge: 'Bestseller',
      isFeatured: true,
      totalBookings: 1240,
      averageRating: 4.9,
      coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
      images: ['https://images.unsplash.com/photo-1540202404-a2f29016b523?w=600'],
      highlights: ['Private Overwater Villa', 'Seaplane Transfer', 'All-Inclusive Meals', 'Snorkeling & Diving', 'Sunset Cruise'],
      inclusions: ['Return airfare from Mumbai', 'Seaplane transfers', 'Overwater villa accommodation (5 nights)', 'All meals (breakfast, lunch, dinner)', 'All non-motorized water sports', 'Snorkeling equipment'],
      exclusions: ['Visa fees', 'Travel insurance', 'Personal expenses', 'Motorized water sports', 'Spa treatments'],
      description: 'Escape to the pristine atolls of the Maldives with our signature overwater villa package. Wake up to turquoise lagoons, snorkel with manta rays, and dine under the stars on a private sandbank.',
      itinerary: [
        { day: 1, title: 'Arrival in Paradise', description: 'Seaplane transfer to your island resort. Welcome cocktail and villa check-in.', activities: ['Seaplane transfer', 'Resort orientation', 'Sunset cocktails'] },
        { day: 2, title: 'Ocean Adventures', description: 'Full-day snorkeling and diving excursions in the world\'s most pristine reefs.', activities: ['Guided snorkeling', 'Dive session', 'Marine biologist talk'] },
        { day: 3, title: 'Island Exploration', description: 'Visit a local Maldivian village and explore uninhabited sandbanks.', activities: ['Village visit', 'Sandbank picnic', 'Traditional music performance'] },
        { day: 4, title: 'Relaxation Day', description: 'Overwater spa treatment, beach yoga, and sunset dolphin cruise.', activities: ['Spa treatment', 'Beach yoga', 'Dolphin cruise'] },
        { day: 5, title: 'Farewell Paradise', description: 'Final breakfast on your deck, leisure time before seaplane back to Malé.', activities: ['Leisurely breakfast', 'Final snorkel', 'Seaplane departure'] },
      ],
    },
    {
      title: 'Dubai City of Gold Experience',
      type: PackageType.INTERNATIONAL,
      destinationId: destMap['Dubai'],
      duration: 4,
      basePrice: 42999,
      discountedPrice: 36999,
      badge: 'Top Rated',
      isFeatured: true,
      totalBookings: 980,
      averageRating: 4.8,
      coverImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
      images: [],
      highlights: ['Burj Khalifa At the Top', 'Desert Safari with BBQ', 'Dubai Mall & Fountain Show', 'Marina Dhow Cruise', 'Abu Dhabi Day Trip'],
      inclusions: ['Return airfare', '4-star hotel (4 nights)', 'Desert safari with BBQ dinner', 'Burj Khalifa tickets', 'All transfers'],
      exclusions: ['Visa fees', 'Travel insurance', 'Personal shopping'],
      description: 'Experience the dazzling extravagance of Dubai — from the world\'s tallest building to golden desert dunes. A perfect blend of modern luxury and timeless Arabian culture.',
      itinerary: [
        { day: 1, title: 'Welcome to Dubai', description: 'Airport pickup, hotel check-in, evening Dubai Mall visit and fountain show.', activities: ['Airport transfer', 'Hotel check-in', 'Dubai Mall', 'Fountain show'] },
        { day: 2, title: 'Sky High & Desert Low', description: 'Morning Burj Khalifa visit, afternoon desert safari with camel riding and BBQ dinner.', activities: ['Burj Khalifa At the Top', 'Camel riding', 'Dune bashing', 'BBQ dinner'] },
        { day: 3, title: 'Abu Dhabi Excursion', description: 'Full day Abu Dhabi tour — Sheikh Zayed Grand Mosque, Ferrari World visit.', activities: ['Grand Mosque', 'Ferrari World', 'Corniche walk'] },
        { day: 4, title: 'Marina & Shopping', description: 'Dubai Marina dhow cruise, Gold Souk and Spice Souk, duty-free shopping.', activities: ['Dhow cruise', 'Gold Souk', 'Spice Souk', 'Duty-free'] },
      ],
    },
    {
      title: 'Kashmir Paradise Houseboat Special',
      type: PackageType.DOMESTIC,
      destinationId: destMap['Kashmir'],
      duration: 5,
      basePrice: 18999,
      discountedPrice: 15999,
      badge: 'Trending',
      isFeatured: true,
      totalBookings: 3400,
      averageRating: 4.9,
      coverImage: 'https://images.unsplash.com/photo-1609766418204-94aae0ecfdfc?w=800',
      images: [],
      highlights: ['Luxury Houseboat Stay on Dal Lake', 'Shikara Ride at Sunrise', 'Gulmarg Gondola Ride', 'Pahalgam Valley Trek', 'Tulip Garden Visit'],
      inclusions: ['Return flights from Delhi', 'Luxury houseboat (2 nights)', 'Hotel accommodation (3 nights)', 'All meals', 'Shikara rides', 'Sightseeing by private cab'],
      exclusions: ['Gondola fees', 'Personal expenses', 'Adventure activities'],
      description: 'Discover why Kashmir is called Paradise on Earth. From the shimmering Dal Lake and its iconic houseboats to snow-capped peaks and blooming meadows.',
      itinerary: [
        { day: 1, title: 'Arrival in Srinagar', description: 'Airport pickup, transfer to luxury houseboat on Dal Lake. Evening shikara ride.', activities: ['Airport transfer', 'Houseboat check-in', 'Shikara ride'] },
        { day: 2, title: 'Srinagar Sightseeing', description: 'Mughal Gardens (Shalimar Bagh, Nishat Bagh), local bazaar walk.', activities: ['Shalimar Bagh', 'Nishat Bagh', 'Hazratbal Shrine', 'Local bazaar'] },
        { day: 3, title: 'Gulmarg Snow Adventure', description: 'Day trip to Gulmarg — Asia\'s highest gondola, snow activities.', activities: ['Gondola ride', 'Skiing (optional)', 'Snow walk', 'Mountain views'] },
        { day: 4, title: 'Pahalgam Valley', description: 'Drive to Pahalgam, horse riding, Betaab Valley, Lidder River picnic.', activities: ['Betaab Valley', 'Chandanwari', 'Horse riding', 'River side lunch'] },
        { day: 5, title: 'Farewell Srinagar', description: 'Morning Tulip Garden visit (seasonal), local shopping, airport drop.', activities: ['Tulip Garden', 'Local handicraft shopping', 'Airport transfer'] },
      ],
    },
    {
      title: 'Romantic Swiss Alps Honeymoon',
      type: PackageType.HONEYMOON,
      destinationId: destMap['Switzerland'],
      duration: 8,
      basePrice: 185000,
      discountedPrice: 169999,
      badge: 'Bestseller',
      isFeatured: true,
      totalBookings: 450,
      averageRating: 5.0,
      coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      images: [],
      highlights: ['First-class Swiss Travel Pass', 'Mount Titlis Cable Car', 'Scenic Train Rides', 'Lucerne Lake Cruise', 'Chocolate Tasting'],
      inclusions: ['Swiss Travel Pass (8 days)', '4-star boutique hotels', 'Breakfast & romantic dinners', 'Mountain excursions', 'Chauffeur arrival/departure'],
      exclusions: ['International flights', 'Personal insurance'],
      description: 'The ultimate romantic escape. Traverse the soaring Swiss Alps, dine by pristine lakes, and experience the quiet luxury of Switzerland.',
      itinerary: [
        { day: 1, title: 'Arrival Lucerne', description: 'Lucerne lake cruise and city tour.', activities: ['Lake cruise', 'Old Town walk'] },
        { day: 2, title: 'Mount Titlis', description: 'Rotating cable car and snow fun.', activities: ['Gondola', 'Ice Cave'] },
        { day: 3, title: 'Jungfraujoch', description: 'Top of Europe train journey.', activities: ['High-altitude train', 'Ice Palace'] },
      ],
    },
    {
      title: 'Maldives Overwater Bliss',
      type: PackageType.HONEYMOON,
      destinationId: destMap['Maldives'],
      duration: 6,
      basePrice: 245000,
      discountedPrice: 220000,
      badge: 'Luxury',
      isFeatured: true,
      totalBookings: 1250,
      averageRating: 5.0,
      coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
      images: ['https://images.unsplash.com/photo-1540202404-a2f29016b523?w=600'],
      highlights: ['Private Overwater Villa', 'Seaplane Transfer', 'All-Inclusive Meals', 'Sunset Cruise', 'Couples Spa'],
      inclusions: ['Return airfare', 'Overwater villa (6 nights)', 'All meals', 'Romantic dinners', 'Spa treatments'],
      exclusions: ['Visa fees', 'Personal expenses'],
      description: 'Pure luxury in a private overwater villa with turquoise views. Perfect for an unforgettable honeymoon.',
      itinerary: [
        { day: 1, title: 'Arrival', description: 'Seaplane transfer to resort, welcome drinks.', activities: ['Sunset Cruise'] },
        { day: 2, title: 'Ocean Romance', description: 'Snorkeling, private beach dinner.', activities: ['Snorkeling', 'Private dinner'] },
      ],
    },
    {
      title: 'Bali Tropical Romance',
      type: PackageType.HONEYMOON,
      destinationId: destMap['Bali'],
      duration: 7,
      basePrice: 125000,
      discountedPrice: 110000,
      badge: 'Exotic',
      isFeatured: false,
      totalBookings: 720,
      averageRating: 4.8,
      coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
      images: [],
      highlights: ['Private Pool Villa Ubud', 'Jungle Sanctuary', 'Couples Cooking Class', 'Rice Terrace Trek', 'Beachfront Dinner'],
      inclusions: ['Private villa (7 nights)', 'Daily breakfast', 'Cooking class', 'Transfers'],
      exclusions: ['Flights', 'Personal shopping'],
      description: 'Private pool villas and jungle sanctuary in Ubud. Experience the spiritual and romantic side of Bali.',
      itinerary: [
        { day: 1, title: 'Ubud Arrival', description: 'Check-in to jungle resort, flower bath.', activities: ['Flower Bath'] },
        { day: 2, title: 'Cultural Immersion', description: 'Rice terrace trek, temple visit.', activities: ['Rice terrace', 'Temple visit'] },
      ],
    },
    {
      title: 'Ladakh High Pass Adventure',
      type: PackageType.ADVENTURE,
      destinationId: destMap['Ladakh'],
      duration: 10,
      basePrice: 45000,
      discountedPrice: 39999,
      badge: 'Elite',
      isFeatured: true,
      totalBookings: 1100,
      averageRating: 4.8,
      coverImage: 'https://images.unsplash.com/photo-1598346762291-aee88549193f?w=800',
      images: ['https://images.unsplash.com/photo-1598346762291-aee88549193f?w=600'],
      highlights: ['Pangong Lake Camping', 'Khardung La Pass (18,000 ft)', 'Nubra Valley Camel Safari', 'Magnetic Hill', 'Zanskar River Rafting'],
      inclusions: ['Fuel-efficient bikes/SUV', 'Tent & hotel stay', 'Oxygen support', 'Professional guide', 'Inner Line Permits'],
      description: 'Ride through the highest motorable passes in the world. A rugged journey for the soul.',
      itinerary: [
        { day: 1, title: 'Leh Acclimatization', description: 'Rest and local Leh market.', activities: ['Relaxation', 'Local tea'] },
        { day: 2, title: 'Nubra Valley', description: 'Via Khardung La Pass.', activities: ['High pass drive', 'Cold desert'] },
      ],
    },
    {
      title: 'Spiti Valley Expedition',
      type: PackageType.ADVENTURE,
      destinationId: destMap['Ladakh'],
      duration: 9,
      basePrice: 38000,
      discountedPrice: 34999,
      badge: 'Offbeat',
      isFeatured: false,
      totalBookings: 940,
      averageRating: 4.9,
      coverImage: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800',
      images: [],
      highlights: ['Key Monastery Visit', 'Chanderatal Lake Camping', 'Hikkim Highest Post Office', '4x4 Off-road Experience'],
      inclusions: ['4x4 SUV transfers', 'Homestay experience', 'Inner Line Permits', 'Expert driver'],
      exclusions: ['Personal expenses', 'Tips'],
      description: 'Discover the Middle Land via 4x4 off-road expedition through rugged terrains.',
      itinerary: [
        { day: 1, title: 'Kaza Arrival', description: 'Arrive in the heart of Spiti.', activities: ['Monastery Visit'] },
        { day: 2, title: 'Hikkim & Langza', description: 'Visit the highest post office.', activities: ['Fossil Hunting'] },
      ],
    },
    {
      title: 'Everest Base Camp Trek',
      type: PackageType.ADVENTURE,
      destinationId: destMap['Kashmir'],
      duration: 14,
      basePrice: 165000,
      discountedPrice: 155000,
      badge: 'Iconic',
      isFeatured: true,
      totalBookings: 430,
      averageRating: 4.9,
      coverImage: 'https://images.unsplash.com/photo-1520209759809-a9bcb6cb3241?w=800',
      images: [],
      highlights: ['Kumbhu Glacier', 'Namche Bazaar', 'Tengboche Monastery', 'Lukla Flight'],
      inclusions: ['Guide & Porter', 'Permits', 'Teahouse accommodation', 'Flights to Lukla'],
      exclusions: ['International flights', 'Insurance'],
      description: 'The ultimate journey to the foot of the world\'s tallest peak. A test of endurance and spirit.',
      itinerary: [
        { day: 1, title: 'Lukla Transfer', description: 'Scenic flight to Lukla.', activities: ['Trekking start'] },
      ],
    },
    {
      title: 'Japan Cherry Blossom Sakura Tour',
      type: PackageType.INTERNATIONAL,
      destinationId: destMap['Japan'],
      duration: 9,
      basePrice: 210000,
      discountedPrice: 189000,
      badge: 'Cultural',
      isFeatured: false,
      totalBookings: 320,
      averageRating: 4.9,
      coverImage: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
      images: [],
      highlights: ['Tokyo Skytree', 'Kyoto Geisha District', 'Osaka Street Food', 'Mt Fuji Day Trip', 'Bullet Train Experience'],
      inclusions: ['JR Pass (7 days)', 'Modern hotels', 'Cultural workshops', 'Guided temple tours'],
      exclusions: ['Visa fees', 'Personal shopping'],
      description: 'Witness the fleeting beauty of Sakura. Experience the harmony of ancient shrines and futuristic neon cities.',
      itinerary: [
        { day: 1, title: 'Neon Tokyo', description: 'Shibuya crossing and Harajuku.', activities: ['City walk', 'Neon lights'] },
        { day: 2, title: 'Kyoto Zen', description: 'Golden Pavilion and Arashiyama.', activities: ['Bamboo forest', 'Tea ceremony'] },
      ],
    },
    {
      title: 'Royal Rajasthan Heritage Trail',
      type: PackageType.DOMESTIC,
      destinationId: destMap['Rajasthan'],
      duration: 7,
      basePrice: 45000,
      discountedPrice: 38500,
      badge: 'Luxury',
      isFeatured: true,
      totalBookings: 2400,
      averageRating: 4.7,
      coverImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800',
      images: [],
      highlights: ['Palace Stays in Udaipur', 'Jaisalmer Desert Camping', 'Jaipur City Palace', 'Camel Safari', 'Puppet Shows'],
      inclusions: ['Heritage Hotel stays', 'Private chauffeur', 'Guided monument tours', 'Traditional dinners'],
      exclusions: ['Monument entry fees'],
      description: 'Step into the land of kings. Experience the grandeur of forts and the legendary hospitality of the desert.',
      itinerary: [
        { day: 1, title: 'Pink City Jaipur', description: 'Amer Fort and Hawa Mahal.', activities: ['Fort visit', 'Local bazaars'] },
        { day: 2, title: 'City of Lakes Udaipur', description: 'Lake Pichola boat ride.', activities: ['Boating', 'Palace tour'] },
      ],
    },
    {
      title: 'Bali Ultimate Adventure & Waves',
      type: PackageType.INTERNATIONAL,
      destinationId: destMap['Bali'],
      duration: 6,
      basePrice: 48000,
      discountedPrice: 42000,
      badge: 'Adventure',
      isFeatured: false,
      totalBookings: 610,
      averageRating: 4.6,
      coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
      images: [],
      highlights: ['Scuba Diving Amed', 'White Water Rafting', 'ATV Forest Trail', 'Uluwatu Surfing', 'Night Trekking'],
      inclusions: ['Adventure gear rental', 'Action camera usage', 'Local guide', 'Transfers'],
      exclusions: ['Insurance'],
      description: 'Not just for beaches. Bali is a playground for the brave.',
      itinerary: [],
    },
    {
      title: 'Goa Luxury Villa Party Week',
      type: PackageType.DOMESTIC,
      destinationId: destMap['Goa'],
      duration: 4,
      basePrice: 35000,
      discountedPrice: 29999,
      badge: 'Premium',
      isFeatured: true,
      totalBookings: 180,
      averageRating: 4.5,
      coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800',
      images: [],
      highlights: ['Private 5BHK Villa', 'Butler Service', 'Yacht Party', 'Exclusive Beach Access', 'Nightclub VIP Entry'],
      inclusions: ['Villa stay', 'Airport drops', 'Bottle service', 'Private chef'],
      exclusions: ['Flights'],
      description: 'The darker, more exclusive side of Goa. Luxury at every corner.',
      itinerary: [],
    },
    {
      title: 'Kerala Ayurvedic Healing Retreat',
      type: PackageType.DOMESTIC,
      destinationId: destMap['Kerala'],
      duration: 10,
      basePrice: 95000,
      discountedPrice: 85000,
      badge: 'Wellness',
      isFeatured: true,
      totalBookings: 890,
      averageRating: 4.9,
      coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800',
      images: [],
      highlights: ['Panchakarma Treatment', 'Yoga & Meditation', 'Organic Diet', 'Herbal Massages', 'Nature Walks'],
      inclusions: ['Doctor consultation', 'All treatments', 'Healing environment', 'Nutritious meals'],
      exclusions: ['Travel to center'],
      description: 'Reset your soul in the lap of nature.',
      itinerary: [],
    },
    {
      title: 'Phuket & Krabi Island Hopping',
      type: PackageType.INTERNATIONAL,
      destinationId: destMap['Thailand'],
      duration: 5,
      basePrice: 28000,
      discountedPrice: 24999,
      badge: 'Budget',
      isFeatured: false,
      totalBookings: 5600,
      averageRating: 4.7,
      coverImage: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800',
      images: [],
      highlights: ['James Bond Island', 'Phi Phi Day Trip', 'Night Market Tour', 'Cave Canoeing', 'Beachfront Stays'],
      inclusions: ['Hotels & breakfast', 'Island transfers', 'Snorkeling masks', 'Guided tours'],
      exclusions: ['Flights'],
      description: 'The classic Thai experience. White sands and blue waters.',
      itinerary: [],
    },
    {
      title: 'South India Temple Run',
      type: PackageType.DOMESTIC,
      destinationId: destMap['Kerala'],
      duration: 6,
      basePrice: 22000,
      discountedPrice: 19999,
      badge: 'Historical',
      isFeatured: false,
      totalBookings: 1200,
      averageRating: 4.8,
      coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800',
      images: [],
      highlights: ['Meenakshi Temple', 'Brihadeeswarar Temple', 'Madurai Local Food', 'Classical Dance Show', 'Spiritual Guidance'],
      inclusions: ['Cultural guides', 'AC Transfers', 'Spiritual tours', 'Traditional hotels'],
      exclusions: ['Alms and donations'],
      description: 'A journey through the architectural marvels of Dravidian culture.',
      itinerary: [],
    },
    {
      title: 'Magical Maldives Honeymoon Bliss',
      type: PackageType.INTERNATIONAL,
      destinationId: destMap['Maldives'],
      duration: 5,
      basePrice: 120000,
      discountedPrice: 105000,
      badge: 'Honeymoon',
      isFeatured: true,
      totalBookings: 890,
      averageRating: 5.0,
      coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
      images: [],
      highlights: ['Candlelight Sandbank Dinner', 'Flower Bed Decoration', 'Champagne Breakfast', 'Private Diving', 'Spa for Couples'],
      inclusions: ['All meals', 'Water villa', 'Romance activities', 'Transfers'],
      exclusions: ['Flights'],
      description: 'Start your forever in the most beautiful place on Earth.',
      itinerary: [],
    },
    {
      title: 'Goa Beach Bliss Weekend',
      type: PackageType.DOMESTIC,
      destinationId: destMap['Goa'],
      duration: 3,
      basePrice: 9999,
      discountedPrice: 8499,
      badge: 'Last Minute',
      isFeatured: false,
      totalBookings: 4500,
      averageRating: 4.6,
      coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800',
      images: [],
      highlights: ['North & South Goa Beaches', 'Water Sports Package', 'Sunset Cruise', 'Flea Market', 'Old Goa Heritage Walk'],
      inclusions: ['Return train/bus tickets', 'Beach resort (3 nights)', 'Breakfast', 'Airport/station transfers', 'Water sports session'],
      exclusions: ['Flights (train included)', 'Lunch & dinner', 'Personal expenses'],
      description: 'Goa never gets old. Sun-kissed beaches, vibrant nightlife, Portuguese heritage, and the freshest seafood on the Indian coast.',
      itinerary: [
        { day: 1, title: 'North Goa Vibes', description: 'Beach exploration, Calangute & Baga, evening at Anjuna flea market.', activities: ['Calangute Beach', 'Baga Beach', 'Anjuna Flea Market', 'Beach shack dinner'] },
        { day: 2, title: 'Water Sports & Sunset', description: 'Morning water sports (parasailing, jet ski, banana boat), sunset Mandovi River cruise.', activities: ['Parasailing', 'Jet skiing', 'Banana boat', 'Sunset cruise'] },
        { day: 3, title: 'South Goa & Heritage', description: 'South Goa beaches, Old Goa churches, spice plantation visit.', activities: ['Palolem Beach', 'Se Cathedral', 'Spice plantation', 'Departure'] },
      ],
    },
    {
      title: 'Bali Island of Gods Retreat',
      type: PackageType.INTERNATIONAL,
      destinationId: destMap['Bali'],
      duration: 7,
      basePrice: 55999,
      discountedPrice: 48999,
      badge: 'Popular',
      isFeatured: true,
      totalBookings: 760,
      averageRating: 4.8,
      coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
      images: [],
      highlights: ['Private Pool Villa', 'Tegallalang Rice Terrace', 'Tanah Lot Temple Sunset', 'Traditional Spa Package', 'Mount Batur Sunrise Trek'],
      inclusions: ['Return airfare', 'Private pool villa (7 nights)', 'Daily breakfast', 'Airport transfers', 'Ubud and Kintamani tours', 'Traditional Balinese spa (1 session)'],
      exclusions: ['Visa on arrival fees', 'Lunch & dinner', 'Personal expenses'],
      description: 'Surrender to the mystical beauty of Bali. Lush rice terraces, ancient Hindu temples, world-class spas, and a culture that will leave you transformed.',
      itinerary: [
        { day: 1, title: 'Arrival in Bali', description: 'Airport pickup to your private villa in Seminyak. Sunset beach walk.', activities: ['Airport pickup', 'Villa check-in', 'Seminyak sunset'] },
        { day: 2, title: 'Ubud Cultural Tour', description: 'Tegallalang Rice Terraces, Ubud Monkey Forest, traditional Kecak dance.', activities: ['Rice terraces', 'Monkey Forest', 'Art market', 'Kecak dance'] },
        { day: 3, title: 'Temple Trail', description: 'Tanah Lot sunset, Uluwatu cliff temple, Jimbaran seafood dinner.', activities: ['Tanah Lot', 'Uluwatu Temple', 'Seafood dinner'] },
        { day: 4, title: 'Volcano Sunrise', description: 'Early morning Mount Batur sunrise trek, hot springs, afternoon spa.', activities: ['Mount Batur trek', 'Hot springs', 'Balinese spa'] },
        { day: 5, title: 'Beach & Leisure', description: 'Nusa Dua beach, water sports, afternoon at leisure.', activities: ['Nusa Dua beach', 'Snorkeling', 'Leisure time'] },
        { day: 6, title: 'Cooking & Culture', description: 'Balinese cooking class, silver jewelry workshop, night market.', activities: ['Cooking class', 'Silver workshop', 'Night market'] },
        { day: 7, title: 'Farewell Bali', description: 'Final morning at villa, shopping at Seminyak, airport transfer.', activities: ['Leisure', 'Shopping', 'Airport transfer'] },
      ],
    },
    {
      title: 'Kerala God\'s Own Country Backwaters',
      type: PackageType.DOMESTIC,
      destinationId: destMap['Kerala'],
      duration: 4,
      basePrice: 14999,
      discountedPrice: 12999,
      badge: 'Nature',
      isFeatured: false,
      totalBookings: 2200,
      averageRating: 4.8,
      coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800',
      images: [],
      highlights: ['Alleppey Houseboat', 'Munnar Tea Plantations', 'Kathakali Dance Show', 'Periyar Wildlife Sanctuary', 'Varkala Cliff Beach'],
      inclusions: ['Return flights from Mumbai/Delhi', 'Houseboat (1 night)', 'Hotel (3 nights)', 'All meals on houseboat', 'Breakfast at hotels', 'Transfers'],
      exclusions: ['Periyar entry fees', 'Personal expenses', 'Lunch & dinner at hotels'],
      description: 'Experience the serene backwaters, misty hill stations, wildlife, and centuries-old art forms of Kerala — India\'s most scenic state.',
      itinerary: [
        { day: 1, title: 'Arrive Cochin', description: 'Fort Kochi walk, Chinese fishing nets, Kathakali performance evening.', activities: ['Fort Kochi', 'Chinese fishing nets', 'Kathakali show'] },
        { day: 2, title: 'Munnar Hills', description: 'Drive to Munnar, Eravikulam National Park, tea plantation tour.', activities: ['Tea plantation tour', 'Eravikulam NP', 'Mattupetty Dam'] },
        { day: 3, title: 'Alleppey Backwaters', description: 'Houseboat cruise through scenic backwaters, village life, toddy tasting.', activities: ['Houseboat cruise', 'Village walk', 'Backwater canoe'] },
        { day: 4, title: 'Varkala & Departure', description: 'Cliff beach at Varkala, Ayurvedic massage, evening departure.', activities: ['Varkala beach', 'Ayurvedic massage', 'Departure'] },
      ],
    },
  ];

  for (const pkg of packages) {
    const slug = pkg.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    await prisma.package.upsert({
      where: { slug },
      update: {},
      create: { ...pkg, slug, reviewCount: Math.floor(Math.random() * 300) + 50 },
    });
  }

  console.log('✅ Packages seeded');

  // ── Deals
  await prisma.deal.upsert({
    where: { code: 'TRIP10' },
    update: {},
    create: {
      title: '10% Off Your First Booking',
      description: 'Use code TRIP10 on your first international package booking',
      code: 'TRIP10',
      discountType: 'PERCENTAGE',
      discountValue: 10,
      minAmount: 20000,
      maxDiscount: 5000,
      usageLimit: 1000,
      validFrom: new Date(),
      validTo: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    },
  });
  await prisma.deal.upsert({
    where: { code: 'FLAT2000' },
    update: {},
    create: {
      title: 'Flat ₹2000 Off Domestic Packages',
      description: 'Flat ₹2000 discount on domestic tour packages',
      code: 'FLAT2000',
      discountType: 'FLAT',
      discountValue: 2000,
      minAmount: 15000,
      usageLimit: 500,
      validFrom: new Date(),
      validTo: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    },
  });

  console.log('✅ Deals seeded');
  console.log('\n🎉 Seeding complete!');
  console.log('Admin: admin@tripinminutes.com / Admin@123');
  console.log('User:  demo@tripinminutes.com  / Demo@123');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
